-- CuratorFit V1.1 seed data

insert into curator_profiles (display_name, bio, accepted_genres, accepted_channels, status)
values
('Unclaimed curator', 'Seed curator profile awaiting claim or opt-out.', array['Melodic Bass','Christian / Inspirational','Cinematic / Ambient'], array['spotify_playlist']::target_type[], 'unclaimed'),
('Founding channel candidate', 'Seed multi-channel profile awaiting manual review.', array['Lo-fi','Ambient','Instrumental'], array['soundcloud_channel','youtube_channel']::target_type[], 'unclaimed'),
('Verified demo curator', 'Demo verified curator profile for UI testing.', array['Indie Pop','Sad Pop','Bedroom Pop'], array['spotify_playlist','blog']::target_type[], 'verified');

insert into promotion_targets (type, url, slug, name, description, genre, genres, moods, fit_tags, audience_size_label, audience_count, contact_method, submission_rules, fit_notes, risk_notes, status, risk_level, trust_score, update_signal)
values
('spotify_playlist','https://open.spotify.com/','melodic-bass-afterglow','Melodic Bass Afterglow','Seed profile for emotional future bass and melodic bass.','Melodic Bass',array['Melodic Bass','Future Bass','Emotional EDM'],array['cinematic','hopeful','drop-focused'],array['future bass','melodic bass','female vocal'],'8.2K playlist followers',8200,'Claim profile before accepting pitches','No guaranteed placement. Review fit before outreach.','Best for emotional electronic tracks with strong melodic drop payoff, guitar warmth, or female vocal hooks.','Seed listing. Needs owner verification and recent-update check before premium review routing.','seed','review',62,'Needs curator verification'),
('soundcloud_channel','https://soundcloud.com/','quiet-room-soundcloud-reposts','Quiet Room Reposts','Future SoundCloud repost channel target.','Lo-fi / Ambient',array['Lo-fi','Ambient','Instrumental'],array['sleepy','soft','low pressure'],array['lo-fi','ambient','instrumental'],'Seed profile',null,'Manual outreach / claim profile','Accepts private links and finished public uploads only. No paid repost guarantees.','Designed for future SoundCloud repost collectives, curator accounts, and micro-label channels.','Do not automate repost promises. Track as discovery target until channel owner claims.','seed','review',58,'Manual review needed'),
('youtube_channel','https://youtube.com/','late-night-visualizer-youtube','Late Night Visualizer Channel','Future YouTube music curator profile.','Cinematic / Electronic',array['Cinematic','Emotional Electronic','Indie Pop'],array['late night','visualizer-friendly','story-driven'],array['visualizer','lyric video','cinematic'],'Seed profile',null,'Public submission/contact link when verified','Needs artwork/visualizer rights and explicit permission before uploads.','For lyric videos, visualizer channels, music discovery uploads, mixes, and genre-specific YouTube curators.','Rights and upload permissions are critical. Never assume permission from a submission alone.','seed','review',61,'Manual review needed'),
('tiktok_creator','https://www.tiktok.com/','hook-first-tiktok-creators','Hook-First TikTok Creators','Future TikTok creator network target.','Short-form',array['Pop','EDM','AI-assisted Music'],array['hooky','emotional','short-form ready'],array['tiktok','short-form','hook'],'Seed profile',null,'Manual creator outreach / invite only','Creator consideration only. No fake engagement, bot views, or undisclosed paid endorsement.','For songs with strong first-5-second hooks, quotable lyrics, dance/meme potential, or emotional POV clips.','Requires sponsorship disclosure workflow and creator approval before paid campaigns.','seed','review',55,'Manual review needed'),
('blog','https://example.com/','faith-heavy-days-blog','Faith & Heavy Days Blog','Future faith-friendly editorial target.','Christian / Inspirational',array['Christian','Inspirational','Singer-songwriter'],array['honest','gentle','hopeful'],array['faith','editorial','story'],'Seed profile',null,'Editorial pitch / claim profile','Faith-friendly, non-preachy, story-driven releases. Editorial coverage not guaranteed.','For future blog/radio/editorial expansion where story and mission matter as much as sonic fit.','Separate editorial review from playlist adds. Avoid pay-for-coverage claims.','seed','low',64,'Manual review needed');

insert into playlists (spotify_url, slug, name, description, genre, moods, fit_tags, followers, status, risk_level, trust_score, update_signal)
values
('https://open.spotify.com/','melodic-bass-afterglow','Melodic Bass Afterglow','Seed profile for emotional future bass, melodic bass, cinematic drops, and guitar-driven electronic records.','Melodic Bass',array['emotional','cinematic','guitar warmth'],array['future bass','melodic bass','emotional edm','female vocal'],8200,'unclaimed','review',62,'Needs curator verification'),
('https://open.spotify.com/','quiet-room-lofi','Quiet Room Lo-fi','For warm instrumental loops, soft drums, sleepy piano, ambient guitar, and low-pressure background music.','Lo-fi / Chill',array['soft','study','night drive'],array['lo-fi','study beats','ambient','instrumental'],5400,'unclaimed','low',71,'Seed listing — manually review before outreach'),
('https://open.spotify.com/','faith-and-heavy-days','Faith for Heavy Days','For worship-adjacent, inspirational, soft Christian, and faith-friendly songs that feel honest and low-pressure.','Christian / Inspirational',array['hopeful','gentle','reflective'],array['christian','worship adjacent','inspirational','soft pop'],3100,'unclaimed','low',68,'Needs owner claim');
